AnonymousFeedback/urls.py
from django.conf.urls import patterns, include, url

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'AnonymousFeedback.views.home', name='home'),
    # url(r'^AnonymousFeedback/', include('AnonymousFeedback.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
    url(r'^feedback_form/', include('feedback_form.urls')),
)

feedback_form/urls.py
from django.conf.urls import *

'''
    these all assume http[s]://URI/feedback_form/ as the base
'''

urlpatterns = patterns('',
    (r'view_feedback', 'feedback_form.views.view_feedback'),
    (r'feedback', 'feedback_form.views.enter_feedback'),
    (r'new_employee', 'feedback_form.views.new_employee'),
   )

feedback_form/models.py
from django.db import models
from django.utils.encoding import smart_unicode

# Create your models here.


class Employee(models.Model):
    name = models.CharField(max_length=255)

    def __unicode__(self):
        return self.name

    class Meta:
        ordering = ['name']

class Feedback(models.Model):
    name = models.ForeignKey(Employee)
    timeframe_start = models.DateField(auto_now=False)
    timeframe_stop = models.DateField(auto_now=False, blank=True, null=True)
    timestamp = models.DateTimeField(auto_now_add=True)
    feedback = models.TextField(blank=False, null=False)

    def __unicode__(self):
        return smart_unicode(self.id)

feedback_form/forms.py
from django import forms
from feedback_form.models import Feedback, Employee

class FeedbackForm(forms.ModelForm):
    class Meta:
        model = Feedback


class EmployeeForm(forms.ModelForm):
    class Meta:
        model = Employee

feedback_form/views.py
from django.shortcuts import render_to_response
from feedback_form.forms import FeedbackForm, EmployeeForm
from feedback_form.models import Feedback, Employee
from django.template import RequestContext
from django.contrib.auth.decorators import permission_required
from django.http import HttpResponseRedirect


# Create your views here.

def enter_feedback(request):
    if request.method == 'POST':
        feedback = Feedback()
        form = FeedbackForm(request.POST, instance=feedback)

        if form.is_valid():
            try:
                feedback = form.save()
                return HttpResponseRedirect('/feedback_form/feedback.html')
            except Exception, e:
                print e
    else:
        form = FeedbackForm()

    return render_to_response('feedback_form/feedback.html', {'form': form}, context_instance=RequestContext(request))

@permission_required('feedback_form.can_add_employee', login_url='/admin/')
def new_employee(request):
    if request.method == 'POST':
        employee = Employee()
        form = EmployeeForm(request.POST, instance=employee)

        if form.is_valid():
            try:
                employee = form.save()
                return HttpResponseRedirect('/feedback_form/new_employee.html')
            except Exception, e:
                print e
    else:
        form = EmployeeForm()

    return render_to_response('feedback_form/new_employee.html', {'form': form}, context_instance=RequestContext(request))

@permission_required('feedback_form.can_delete_feedback', login_url='/admin/')
def view_feedback(request):
    feedback = Feedback.objects.all().order_by('-timestamp')
    employees = Employee.objects.all()

    return render_to_response('feedback_form/view_feedback.html', {'feedback': feedback, 'employees': employees}, context_instance=RequestContext(request))

templates/base.html
<!doctype html>
<html lang="en">
<head>
    <style type = "text/css">
        #container{
            display: block;
            width: 600px;
            margin: auto;
            padding: 10px;
            vertical-align: top;
            border: solid thin black;
            box-shadow: 2px 2px 2px #888888;
        }

        label{
            width: 200px;
        }

        label, input{
            display: inline-block;
            vertical-align: top;
            margin-bottom: 5px;
            margin-right: 5px;
        }

        .feedbackContainer{
            box-shadow: 2px 2px 2px #888888;
            margin-bottom: 25px;
        }
        .feedbackContainer div{
            padding: 10px;
            vertical-align: top;
            border: solid thin black;
        }
        .infoLabel{
            vertical-align: top;
            width: 130px;
            position: relative;
            left: 20px;
        }

        .infospan{
            width: 400px;
        }

        .infospan, .infoLabel{
            display: inline-block;
            padding: 5px;
        }

    </style>
<link rel="stylesheet" href="http://code.jquery.com/ui/1.10.3/themes/smoothness/jquery-ui.css" />
</head>
<body>
    <script src="/static/scripts/jquery-1.9.1.js"></script>
<script src="/static/scripts/jquery-ui-v1.10.3.js"></script>

    {% block bodyblock %}
    {% endblock %}
</body>
</html>

templates/feedback_form/feedback.html
{% extends 'base.html' %}
{% block bodyblock %}
<div id = "container">
    <form action="" method="post" enctype="multipart/form-data" id="feedbackForm">
        {% csrf_token %}
        <label class='leftlabel'>{{form.name.label}}:</label> {{form.name}}<br />
        <input type = 'radio' class = 'datePicker' name = 'timeFrameSelection' value = 'Date' checked> Date
        <input type = 'radio' class = 'datePicker' name = 'timeFrameSelection' value = 'Range'> Range<br />
        <label id='id_timeframe_start_label'>Date:</label> {{form.timeframe_start}}<br />
        <label id='id_timeframe_stop_label' style='display: none; width: 200px; margin-bottom: 5px; margin-right: 5px; vertical-align: top'>Range End:</label>
        <input id="id_timeframe_stop" type="text" name="timeframe_stop" style='display: none; margin-bottom: 5px; margin-right: 5px; vertical-align: top'>
        <span style = 'display: block'>
        <label>{{form.feedback.label}}:</label> {{form.feedback}}
        </span>
        <input type="submit" value="Submit"/>
    </form>
</div>
<script>
$(function(){
    $('#id_timeframe_start').datepicker();
    $('#id_timeframe_stop').datepicker();
});
$('.datePicker').change(function(){
    var radioSelected = $('input[name=timeFrameSelection]:checked', '#feedbackForm').val();
    console.log(radioSelected);
    if(radioSelected == 'Date'){
        $('#id_timeframe_stop').css('display', 'none');
        $('#id_timeframe_stop_label').css('display', 'none')
        $('#id_timeframe_start_label').text('Date')
    }
    else if(radioSelected == 'Range'){
        $('#id_timeframe_stop').css('display', 'inline-block');
        $('#id_timeframe_stop_label').css('display', 'inline-block')
        $('#id_timeframe_start_label').text('Range Start')
    };
});
var radioSelected = $('input[name=timeFrameSelection]:checked', '#feedbackForm').val();
console.log(radioSelected);
</script>
{% endblock %}

templates/feedback_form/new_employee.html
{% extends 'base.html' %}
{% block bodyblock %}
<div id='container'>
	<form action="" method="post" enctype="multipart/form-data" id="feedbackForm">
	    {% csrf_token %}
	<table>
	    {{form.as_table}}
	</table>
	<input type="submit" value="Submit"/>
	</form>
</div>
{% endblock %}

templates/feedback_form/view_feedback.html
{% extends 'base.html' %}
{% block bodyblock %}

<div id="container">
    <select name="employees" id="employeeSelect">
        <option value = "none">--</option>
        {% for employee in employees %}
            <option value="{{employee.name}}">{{employee.name}}</option>
        {% endfor %}
    </select>
    <br /><br />
    {% for i in feedback %}
    <div class="feedbackContainer">
            <div class = '{{i.name}}' style = 'display: none'>
                <span class = 'infoLabel' id ="top">Date:</span> <span class='infospan' id="top">{{i.timeframe_start}}{% if i.timeframe_stop %} - {{i.timeframe_stop}}{% endif %} ({{i.timestamp}})</span><br />
                <span class = 'infoLabel' id="bottom">Feedback:</span> <span class='infospan' id="bottom">{{i.feedback|linebreaksbr}}</span><br />
            </div>
    </div>
    {% endfor %}
</div>
<script>
$('#employeeSelect').change(function(){
    var selectedEmployee = $('#employeeSelect').val()
    console.log(selectedEmployee)
    $('#container div').each(function(i){
        if($(this).attr('class')==selectedEmployee){
            $(this).css('display', 'block');
        }else if($(this).attr('class')!='feedbackContainer'){
            $(this).css('display', 'none');
        };
        console.log($(this).attr('class'));
    });
    //$('.'+selectedEmployee).css('display', 'block');
});
</script>
{% endblock %}